PROMPT:
  - KEY: "JIRA-TASK"
    LABEL: "Jira task ID"
  - KEY: "CHANGE"
    LABEL: "Select the type of change:"
    OPTIONS:
      - VALUE: "build"
        DESC: "Changes that affect the build system or external dependencies (example: dep, npm)"
      - VALUE: "ci"
        DESC: "Changes to our CI configuration files and scripts (example: Drone, stack)"
      - VALUE: "docs"
        DESC: "Documentation only changes"
      - VALUE: "feat"
        DESC: "A new feature"
      - VALUE: "fix"
        DESC: "A bug fix"
      - VALUE: "perf"
        DESC: "A code change that improves performance"
      - VALUE: "refactor"
        DESC: "A code change that neither fixes a bug nor adds a feature"
      - VALUE: "style"
        DESC: "Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)"
      - VALUE: "test"
        DESC: "Adding missing tests or correcting existing tests"
  - KEY: "MESSAGE"
    LABEL: "Commit message"
TEMPLATE: "{{JIRA-TASK}} ({{CHANGE}}): {{MESSAGE}}"
